spring:
  datasource:
    password: f718fb8fc388f4c749e3d76be262376b1cab15ca7a84eae81c31e8f05fd8e6e4
    url: postgres://fpoftlqgrvxpvh:f718fb8fc388f4c749e3d76be262376b1cab15ca7a84eae81c31e8f05fd8e6e4@ec2-34-235-108-68.compute-1.amazonaws.com:5432/d2flgo3uli11na
    username: fpoftlqgrvxpvh

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    generate-ddl: TRUE
    hibernate:
      ddl-auto: update
    show-sql: true
   
paypal:
    client:
        id: AdYEPgUGiAtOX4kukiqpn6r5ez3SI9MIr20KHKVbYF_rydU-j8ix3BSzPu3JhSsJVYZeLA2NdTNPEYXx
        secret: EAg-meTGU_KOynLKY4MNz9iRHpyVXsW2oRNu3plEtYKaAvhvGRO-i-vEhLpdmAMp5hc5utGm2hhH2aLr
    mode: sandbox
    

